[[redirects]]
  from = "/guide/"
  to = "/guide/introduction.html"

[[redirects]]
 from = "guide/doc-style-guide.html"
 to = "/guide/contributing/doc-style-guide.html"

[[redirects]]
  from = "/guide/writing-guide.html"
  to = "/guide/contributing/writing-guide.html"

[[redirects]]
  from = "/mojang/*"
  to = "https://sessionserver.mojang.com/session/minecraft/profile/"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[build]
  command = "npm run build"
  publish = "src/.vuepress/dist"